// Css
import "./globals.css"
// Fonts
import { fontMono, fontSans } from "./fonts"
import { Footer, Header } from "@/components"
// Components

export const metadata = {
  title: "VAL",
  description: "Generated by Next Js",
  robots: {
    index: false,
    follow: false,
    nocache: true,
    googleBot: {
      index: false,
      follow: false,
      noimageindex: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} ${fontMono.variable} antialiased font-mono font-normal text-text_color`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
